FROM mcr.microsoft.com/mssql/server:2017-GA-ubuntu

ENV CHECK_POLICY=OFF
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Dev123456789
ENV MSSQL_PID=Developer

COPY ./setup/* /setup/

RUN ( /opt/mssql/bin/sqlservr --accept-eula & ) | grep -q "Service Broker manager has started" \
    && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD} -i /setup/instawdb.sql \
    && pkill sqlservr 

CMD ["/opt/mssql/bin/sqlservr"]